# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz_copy_v2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(541, 383)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.boton_start = QtWidgets.QPushButton(self.centralwidget)
        self.boton_start.setGeometry(QtCore.QRect(270, 220, 151, 41))
        self.boton_start.setStyleSheet("background-color: rgb(239, 255, 252);\n"
"")
        self.boton_start.setObjectName("boton_start")
        self.opciones = QtWidgets.QGroupBox(self.centralwidget)
        self.opciones.setGeometry(QtCore.QRect(10, 120, 151, 181))
        self.opciones.setObjectName("opciones")
        self.copiar_subdirectorios = QtWidgets.QCheckBox(self.opciones)
        self.copiar_subdirectorios.setEnabled(True)
        self.copiar_subdirectorios.setGeometry(QtCore.QRect(10, 50, 131, 31))
        self.copiar_subdirectorios.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.copiar_subdirectorios.setAutoFillBackground(False)
        self.copiar_subdirectorios.setChecked(True)
        self.copiar_subdirectorios.setTristate(False)
        self.copiar_subdirectorios.setObjectName("copiar_subdirectorios")
        self.crear_log = QtWidgets.QCheckBox(self.opciones)
        self.crear_log.setGeometry(QtCore.QRect(10, 80, 131, 17))
        self.crear_log.setObjectName("crear_log")
        self.text_hilos_trabajo = QtWidgets.QLabel(self.opciones)
        self.text_hilos_trabajo.setGeometry(QtCore.QRect(10, 20, 81, 21))
        self.text_hilos_trabajo.setObjectName("text_hilos_trabajo")
        self.numero_hilos = QtWidgets.QSpinBox(self.opciones)
        self.numero_hilos.setGeometry(QtCore.QRect(100, 20, 42, 22))
        self.numero_hilos.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.numero_hilos.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.numero_hilos.setMinimum(1)
        self.numero_hilos.setMaximum(10)
        self.numero_hilos.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.numero_hilos.setProperty("value", 5)
        self.numero_hilos.setObjectName("numero_hilos")
        self.modos = QtWidgets.QGroupBox(self.centralwidget)
        self.modos.setGeometry(QtCore.QRect(180, 120, 341, 51))
        self.modos.setObjectName("modos")
        self.copiar = QtWidgets.QRadioButton(self.modos)
        self.copiar.setGeometry(QtCore.QRect(10, 20, 82, 21))
        self.copiar.setChecked(True)
        self.copiar.setObjectName("copiar")
        self.mover = QtWidgets.QRadioButton(self.modos)
        self.mover.setGeometry(QtCore.QRect(110, 20, 82, 21))
        self.mover.setObjectName("mover")
        self.rutas = QtWidgets.QGroupBox(self.centralwidget)
        self.rutas.setGeometry(QtCore.QRect(10, 10, 521, 101))
        self.rutas.setTitle("")
        self.rutas.setObjectName("rutas")
        self.text_origen = QtWidgets.QLabel(self.rutas)
        self.text_origen.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.text_origen.setObjectName("text_origen")
        self.ruta_origen = QtWidgets.QLineEdit(self.rutas)
        self.ruta_origen.setGeometry(QtCore.QRect(90, 10, 421, 20))
        self.ruta_origen.setObjectName("ruta_origen")
        self.text_destino = QtWidgets.QLabel(self.rutas)
        self.text_destino.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.text_destino.setObjectName("text_destino")
        self.ruta_destino = QtWidgets.QLineEdit(self.rutas)
        self.ruta_destino.setGeometry(QtCore.QRect(90, 60, 421, 20))
        self.ruta_destino.setObjectName("ruta_destino")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CopyFiles"))
        self.boton_start.setText(_translate("MainWindow", "Empezar"))
        self.opciones.setTitle(_translate("MainWindow", "OPCIONES"))
        self.copiar_subdirectorios.setText(_translate("MainWindow", "COPIAR SUBDIRECTORIOS"))
        self.crear_log.setText(_translate("MainWindow", "CREAR LOG"))
        self.text_hilos_trabajo.setText(_translate("MainWindow", "HILOS"))
        self.modos.setTitle(_translate("MainWindow", "MODOS"))
        self.copiar.setText(_translate("MainWindow", "COPIAR"))
        self.mover.setText(_translate("MainWindow", "MOVER"))
        self.text_origen.setText(_translate("MainWindow", "Carpeta Origen"))
        self.text_destino.setText(_translate("MainWindow", "Carpeta Destino"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
